### ISSUE TITLE
Switch support when? 

### ISSUE THREAD

**Issue by garylkz** [o7-Fire/Mindustry-Ozone#19]

**Comment by Itzbenz** [comment]
![unknown-18](https://user-images.githubusercontent.com/49940811/108345229-50f76100-71de-11eb-89db-74a157154d2d.png)

**Comment by ghost** [comment]
![082051600_1538713870-040684600_1494934887-hitler_1881083c__1_](https://user-images.githubusercontent.com/46597698/108356996-d0f5e900-7227-11eb-98f2-1ea5a65b6e82.jpg)
