### ISSUE TITLE
4 year-old hand-to-hand sing-a-long installation guide video when?

### ISSUE THREAD

**Issue by garylkz** [o7-Fire/Mindustry-Ozone#22]
this app is good my grandson want to try it but he know no shit

**Comment by ghost** [comment]
![pinochet](https://user-images.githubusercontent.com/46597698/110134320-38a35b00-7e08-11eb-931a-01cbdf6150a4.jpg)

**Comment by Itzbenz** [comment]
to use it you need to answer this question
1. who is nietzsche
2. what is 1984
3. what is 1488
4. have you read 1984
5. have you read 1488

**Comment by Volas171** [comment]
sir there's already a installation video its on twitch and its named ozone tutorial

**Comment by Itzbenz** [comment]
goddam pfp

**Comment by Itzbenz** [comment]
> this app is good my grandson want to try it but he know no shit

sir this is wendy

**Comment by Volas171** [comment]
> goddam pfp

stfu
ive seen worse
