### ISSUE TITLE
there are 999999999999 as tags, and the releases are fucked up

### ISSUE THREAD

**Issue by ghost** [o7-Fire/Mindustry-Ozone#29]
please delete them

**Comment by Itzbenz** [comment]
gay

**Comment by Itzbenz** [comment]
how

**Comment by ghost** [comment]
you can, jsut give me perms

**Comment by Itzbenz** [comment]
die hard

**Comment by Itzbenz** [comment]
you spamming discord debil

**Comment by ghost** [comment]
oh I am?

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by Itzbenz** [comment]
![](https://tenor.com/view/19dollar-fortnite-card-fortnite-card-19-gif-20242831)

**Comment by ghost** [comment]
1.

**Comment by Itzbenz** [comment]
![4633](https://user-images.githubusercontent.com/49940811/110438667-e8055980-80b6-11eb-8683-faaa5434539e.jpg)

**Comment by ghost** [comment]
1.

**Comment by Itzbenz** [comment]
![h](https://user-images.githubusercontent.com/49940811/110438778-023f3780-80b7-11eb-9348-d2894df395f1.png)

**Comment by ghost** [comment]
1.

**Comment by Itzbenz** [comment]
![Screenshot_2020-12-14_13-15-51](https://user-images.githubusercontent.com/49940811/110438894-1be07f00-80b7-11eb-95eb-5c2b93f0bf16.png)

**Comment by Itzbenz** [comment]
![hhhh](https://user-images.githubusercontent.com/49940811/110438964-2c90f500-80b7-11eb-8dcc-5bd0d9c5b5c0.png)

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by Itzbenz** [comment]
![BRRRRRR](https://user-images.githubusercontent.com/49940811/110439081-4fbba480-80b7-11eb-8d63-e20c7e67bbd7.png)

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by ghost** [comment]
1.

**Comment by Itzbenz** [comment]
![StocksBrainlet](https://user-images.githubusercontent.com/49940811/110439124-5d712a00-80b7-11eb-9f7a-fe3e5aacd3f7.png)

**Comment by Itzbenz** [comment]
![BlackHoleBrainlet](https://user-images.githubusercontent.com/49940811/110439193-724dbd80-80b7-11eb-8ada-ae2659a0e2ea.png)

**Comment by Itzbenz** [comment]
![PitBrainlet](https://user-images.githubusercontent.com/49940811/110439226-7f6aac80-80b7-11eb-8a71-84f2c77fd743.png)

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/46597698/110439229-2c621b00-80f2-11eb-8b31-e378fa828527.mp4

**Comment by Itzbenz** [comment]
![image](https://user-images.githubusercontent.com/49940811/110439273-8db8c880-80b7-11eb-8cc8-6dd3bc20ae54.png)
wtf dude

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/46597698/110439660-aeeada80-80f2-11eb-9d44-dcc1d0a74a60.mp4

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/46597698/110439708-bd38f680-80f2-11eb-8ea9-67719cd7b187.mp4

**Comment by Itzbenz** [comment]
stalin died for your sin

**Comment by ghost** [comment]
jesus breathed so we dont have to

**Comment by Itzbenz** [comment]
![Uploading CavedInBrainlet.png…]()

**Comment by nekonya3031** [comment]
Go to durka @Nexity

**Comment by guncatt** [comment]
> gay

I would agree
