### ISSUE TITLE
Need help with downloading o7.

### ISSUE THREAD

**Issue by Zarq0** [o7-Fire/Mindustry-Ozone#36]
Ozone is deleted from mod browser, Is there any other way to download it?

**Comment by ghost** [comment]
https://github.com/o7-Fire/Mindustry-Ozone/wiki/Download

**Comment by Zarq0** [comment]
I tried it but I can't download any file from there. @Nexity

**Comment by ghost** [comment]
hmm

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46597698/112982400-05e24d80-918f-11eb-90a0-1b6693cf4eac.png)
click this

**Comment by ghost** [comment]
https://github.com/o7-Fire/Mindustry-Ozone/actions/runs/696835892

**Comment by Zarq0** [comment]
I did.

**Comment by ghost** [comment]
what pops up?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46597698/112982590-3c1fcd00-918f-11eb-8865-85ad8fa66de9.png)
it should be like this

**Comment by Zarq0** [comment]
I can just copy the name but not download the file.

**Comment by ghost** [comment]
are you on android?

**Comment by Zarq0** [comment]
> ![image](https://user-images.githubusercontent.com/46597698/112982590-3c1fcd00-918f-11eb-8865-85ad8fa66de9.png)
> it should be like this
> 

Nothing pops up. I just can't download it.

**Comment by ghost** [comment]
[Mindustry-Core (5).zip](https://github.com/o7-Fire/Mindustry-Ozone/files/6228690/Mindustry-Core.5.zip)
try clicking this and it should work

**Comment by Zarq0** [comment]
Works, Thanks.

**Comment by ghost** [comment]
you're welcome

**Comment by ghost** [comment]
also we are working on a new mod, so we wont be updating ozone for a while

**Comment by Zarq0** [comment]
Good to know.
